name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  binder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ghostscript
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      # Adapted from https://askubuntu.com/a/524368
      - run: ./binder/execute_notebooks.sh
      # adapted from https://unix.stackexchange.com/a/545630
      - run: find -type f -name "*.pdf" -exec bash -c 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dBATCH -dQUIET -sOutputFile="new.pdf" "{}"; rm "{}"; mv "new.pdf" "{}";' {} \;
      - run: rm -rf .git
      - run: git init
      - uses: fregante/setup-git-user@v1
      - run: git commit --allow-empty -m "Initial commit"
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: binder # The branch the action should deploy to.
          folder: "${{ github.workspace }}" # The folder the action should deploy.

  docker-teximage-build:
    name: Docker Tex Image Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: "GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/${{ github.event.repository.name }}
          registry: ghcr.io
          path: ./tex/
          add_git_labels: true
  latex:
    name: Latex Build
    runs-on: ubuntu-20.04
    needs:
      - docker-teximage-build
    container:
      image: ghcr.io/mmore500/${{ github.event.repository.name }}:GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make -C /opt/${{ github.event.repository.name }}/tex
      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: manuscript
          path: /opt/${{ github.event.repository.name }}/tex/${{ github.event.repository.name }}-draft.pdf
